export const GET_COMPLETED_RIDES_REQUEST="GET_COMPLETED_RIDES_REQUEST";
export const GET_COMPLETED_RIDES_SUCCESS ='GET_COMPLETED_RIDES_SUCCESS';
export const GET_COMPLETED_RIDES_FAILURE='GET_COMPLETED_RIDES_FAILURE';