// get current ride of driver
export const GET_CURRENT_RIDE_REQUEST = 'GET_CURRENT_RIDE_REQUEST';
export const GET_CURRENT_RIDE_SUCCESS = 'GET_CURRENT_RIDE_SUCCESS';
export const GET_CURRENT_RIDE_FAILURE = 'GET_CURRENT_RIDE_FAILURE';


// GET ALLOCATED RIDE
export const GET_ALLOCATED_RIDE_REQUEST = 'GET_ALLOCATED_RIDE_REQUEST';
export const GET_ALLOCATED_RIDE_SUCCESS = 'GET_ALLOCATED_RIDE_SUCCESS';
export const GET_ALLOCATED_RIDE_FAILURE = 'GET_CURRENT_RIDE_FAILURE';


// 

export const COMPLETED_RIDE_SUCCESS="COMPLETED_RIDE_SUCCESS";
